# Generated by Django 3.1.2 on 2020-10-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viedo', '0002_auto_20201021_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viedo',
            name='playname',
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
        migrations.DeleteModel(
            name='Viedo',
        ),
    ]
