# Generated by Django 3.1.1 on 2020-12-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viedo', '0004_playlist_viedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='img',
            field=models.ImageField(upload_to='E:\\DjangoProjects\\unq_coder\\media'),
        ),
    ]
